USE [master]
GO

/****** Object:  Database [PVC]    Script Date: 29/04/2022 15:19:23 ******/
CREATE DATABASE [PVC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PVC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PVC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PVC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PVC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PVC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PVC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PVC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PVC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PVC] SET ARITHABORT OFF 
GO

ALTER DATABASE [PVC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PVC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PVC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PVC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PVC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PVC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PVC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PVC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PVC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PVC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PVC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PVC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PVC] SET  MULTI_USER 
GO

ALTER DATABASE [PVC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PVC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PVC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PVC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PVC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PVC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PVC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PVC] SET  READ_WRITE 
GO


